name: Publish
on:
  push:
    branches:
      - master
      - main

jobs:
  publish:
    name: Publish
    uses: "chlbri/node-github-actions/.github/workflows/publish.yml"
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
