name: Admin Upgarde

on:
  # Déclenchement manuel
  workflow_dispatch:
  # Cron chaque premier du mois à 4h UTC
  schedule:
    - cron: "0 4 1 * *"

jobs:
  upgrade:
    uses: chlbri/node-github-actions/.github/workflows/upgrade.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
